### ISSUE TITLE
Actualizar tablas en el diccionario de datos

### ISSUE THREAD

**Issue by AndreyPootMay** [AndreyPootMay/cursos#9]
Actualizar nombres de las tablas, campos etc. dentro del documento de [drive](https://docs.google.com/spreadsheets/d/1LSEplvcyjRUwk2t5sZo8XgJa7CZDKiOSyKrZoot0B_U/edit?usp=drive_web&ouid=109175408057333903015).

- [x] Registrar tablas nuevas
- [x] Campos nuevos
- [x] Correcciones de cada campo

**Comment by felitito90** [comment]
terminado, favor de revisarlo.

**Comment by AndreyPootMay** [comment]
revisado
